name: ci

on:
  push:
    branches: master

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - python_version: "2.7"
            odoo_version: "8.0"
          - python_version: "2.7"
            odoo_version: "9.0"
          - python_version: "2.7"
            odoo_version: "10.0"
          - python_version: "3.5"
            odoo_version: "11.0"
          - python_version: "3.6"
            odoo_version: "12.0"
          - python_version: "3.6"
            odoo_version: "13.0"
          - python_version: "3.6"
            odoo_version: "14.0"
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to ghcr.io
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            python_version=${{ matrix.python_version }}
            odoo_version=${{ matrix.odoo_version }}
          tags: ghcr.io/${{ github.repository_owner }}/oca-ci:py${{ matrix.python_version }}-odoo${{matrix.odoo_version }}-latest
          push: true
          cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/oca-ci:py${{ matrix.python_version }}-odoo${{matrix.odoo_version }}-latest
          cache-to: type=inline
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
